name: ${project.name}
version: ${project.version}
main: com.bencodez.advancedmobcontrol.AdvancedMobControlMain
api-version: 1.13
author: BenCodez
libraries:
  - org.openjdk.nashorn:nashorn-core:15.3
commands:
  advancedmobcontrol:
    description: Plugin command
    aliases: [mobcontrol]